[package]
name = "capstone"
version = "0.0.2"
authors = ["Richo Healey <richo@psych0tik.net>"]

description = "Bindings to capstone engine (http://capstone-engine.org/)"
license = "MIT"
repository = "https://github.com/richo/capstone-rs"
