[package]
name = "capstone3"
version = "0.1.0"
authors = ["m4b <m4b.github.io@gmail.com>", "Richo Healey <richo@psych0tik.net>"]
description = "High level bindings to capstone disassembly engine (http://capstone-engine.org/)"
license = "MIT"
repository = "https://github.com/m4b/capstone-rs"

[dependencies]
libc = "0.2"
capstone-sys = { git = "https://github.com/m4b/capstone-sys.git", rev = "da056fcb93add71aef071780ecee30c92ebabab7" }

[features]
default = []
use_bundled_capstone_bindings = ["capstone-sys/use_bundled_capstone_bindings"]
use_system_capstone = ["capstone-sys/use_system_capstone"]
build_capstone_cmake = ["capstone-sys/build_capstone_cmake"]
