[package]
name = "capstone"
version = "0.1.0"
authors = ["Richo Healey <richo@psych0tik.net>", "m4b <m4b.github.io@gmail.com>"]
description = "High level bindings to capstone disassembly engine (http://capstone-engine.org/)"
license = "MIT"
repository = "https://github.com/richo/capstone-rs"

[dependencies]
libc = "0.2"
capstone-sys = "0.1"

[features]
default = []
build_capstone = ["capstone-sys/build_src_cmake"]
